const GAMES = [
  { title: "Age of Empires IV: Anniversary Edition", hours: 12.5, tags: ["RTS", "Strategy"], steamAppId: 1466860, blurb: "Build a medieval town, raise an army, and fight large historical battles." },
  { title: "Among Us", hours: 1.1, tags: ["Party", "Co-op"], steamAppId: 945360, blurb: "A short social game where you spot the impostor on a spaceship." },
  { title: "Apex Legends™", hours: 2.7, tags: ["FPS", "Co-op"], steamAppId: 1172470, blurb: "A fast squad shooter where heroes slide, jump, and revive each other." },
  { title: "ARC Raiders", hours: 30.7, tags: ["FPS", "Co-op"], steamAppId: 1808500, blurb: "Drop into a ruined Earth, fight machines, and extract with what you can carry." },
  { title: "Arma 3", hours: 40.9, tags: ["FPS", "Sim"], steamAppId: 107410, blurb: "A huge military sandbox with realistic soldiers, vehicles, and missions." },
  { title: "ARMORED CORE™ VI FIRES OF RUBICON™", hours: 23.3, tags: ["Action"], steamAppId: 1888160, blurb: "Pilot a custom mech through flashy, difficult mission-based combat." },
  { title: "BACKROOMS: APPREHENSION", hours: 1.8, tags: ["Horror", "Co-op"], steamAppId: 2234150, blurb: "Escape yellow rooms with friends while a shapeshifter hides among you." },
  { title: "Balatro", hours: 25.3, tags: ["Card"], steamAppId: 2379780, blurb: "A poker roguelike about building absurd hands and chasing one more round." },
  { title: "Baldur's Gate 3", hours: 47.6, tags: ["RPG", "Story"], steamAppId: 1086940, blurb: "A long fantasy adventure where your choices, party, and dice rolls shape the story." },
  { title: "BattleBit Remastered", hours: 0.3, tags: ["FPS"], steamAppId: 671860, blurb: "A low-poly battlefield shooter with huge matches and simple gunplay." },
  { title: "Battlefield™ 1", hours: null, tags: ["FPS"], steamAppId: 1238840, blurb: "A cinematic World War I shooter with tanks, planes, and large battles." },
  { title: "Battlefield™ V", hours: 3.1, tags: ["FPS"], steamAppId: 1238810, blurb: "A World War II shooter built around squads, vehicles, and big maps." },
  { title: "Bloons TD 6", hours: 28.3, tags: ["Strategy"], steamAppId: 960090, blurb: "Place monkey towers along a track and pop ever-tougher waves of balloons." },
  { title: "Borderlands 2", hours: null, tags: ["FPS", "Co-op"], steamAppId: 49520, blurb: "A loud loot shooter with jokes, weird guns, and co-op mayhem." },
  { title: "Borderlands 3", hours: 2.9, tags: ["FPS", "Co-op"], steamAppId: 397540, blurb: "Hunt legendary guns with friends across a colorful, chaotic galaxy." },
  { title: "Borderlands 4", hours: 27.7, tags: ["FPS", "Co-op"], steamAppId: 1285190, blurb: "The next loot-and-shoot adventure, built to play with other people." },
  { title: "Brawlhalla", hours: 1.1, tags: ["Fighting"], steamAppId: 291550, blurb: "A free platform fighter: jump in, hit people off the stage, rematch." },
  { title: "Broken Arrow", hours: 311, tags: ["RTS"], steamAppId: 1604270, blurb: "Modern war in real time, with combined armies, vehicles, and careful tactics." },
  { title: "Brotato", hours: 2, tags: ["Action"], steamAppId: 1942280, blurb: "A tiny potato with too many guns survives wave after wave of aliens." },
  { title: "Call of Duty®", hours: 19.7, tags: ["FPS"], steamAppId: 1938090, blurb: "The current Call of Duty hub: fast multiplayer matches and military campaigns." },
  { title: "Call of Duty®: Modern Warfare® II", hours: null, tags: ["FPS"], steamAppId: 3595230, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3595230/ce4d5e53b36cb9d3c4309d1df72bf8663bbbc7ef/header.jpg", blurb: "A modern military shooter with tight gunfights and a set-piece campaign." },
  { title: "CARRION", hours: 0.8, tags: ["Horror", "Action"], steamAppId: 953490, blurb: "You are the monster, crawling through a lab and eating the people hunting you." },
  { title: "Chained Together", hours: 7.2, tags: ["Co-op", "Party"], steamAppId: 2567870, blurb: "Climb out of hell while physically chained to your friends." },
  { title: "Clone Drone in the Danger Zone", hours: 19.7, tags: ["Action"], steamAppId: 597170, blurb: "Sword-fight robots in a game-show arena where one hit takes off a limb." },
  { title: "Content Warning", hours: null, tags: ["Horror", "Co-op"], steamAppId: 2881650, blurb: "Film scary dives with friends, then watch the footage back together." },
  { title: "CONTROL Ultimate Edition", hours: 12.6, tags: ["Action", "Story"], steamAppId: 870780, blurb: "A strange government building, telekinetic combat, and a mystery that keeps shifting." },
  { title: "Counter-Strike 2", hours: 5.9, tags: ["FPS"], steamAppId: 730, blurb: "Round-based gunfights where one good shot decides the round." },
  { title: "Crab Game", hours: 0.1, tags: ["Party"], steamAppId: 1782210, blurb: "Silly deadly minigames you play with a crowd of other people." },
  { title: "Crusader Kings II", hours: 87.3, tags: ["Strategy"], steamAppId: 203770, blurb: "Rule a medieval dynasty: marriages, plots, wars, and messy heirs." },
  { title: "Dale & Dawson Stationery Supplies", hours: 4.4, tags: ["Party", "Co-op"], steamAppId: 2920570, blurb: "An office party game about slackers pretending to work while the manager hunts them." },
  { title: "Dark Deception", hours: 0.5, tags: ["Horror"], steamAppId: 332950, blurb: "Run through nightmare mazes while something cute and awful chases you." },
  { title: "Dead as Disco", hours: 0.8, tags: ["Action", "Fighting"], steamAppId: 3404260, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3404260/ae0f4b71735adf4f2494ecb7914fcbafee215277/header.jpg", blurb: "A beat-em-up where every punch lands on the music." },
  { title: "Dead as Disco Demo", hours: 3.2, tags: ["Action", "Fighting"], steamAppId: 3763830, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3763830/24190d481870bd662a19557192c029e9bb4052fe/header.jpg", blurb: "The demo of the rhythm brawler: short, stylish, and punchy." },
  { title: "Dead Island 2", hours: 17.4, tags: ["Action", "Co-op"], steamAppId: 934700, blurb: "Smash zombies in a sunny, gory Los Angeles, best played with a friend." },
  { title: "Dead Space", hours: 16.2, tags: ["Horror"], steamAppId: 1693980, blurb: "A tense space-horror walk through a dead ship full of body horror." },
  { title: "Deadlock", hours: 0.3, tags: ["Action"], steamAppId: 1422450, blurb: "A hero shooter mixed with lane strategy: shoot, push, and take the patron." },
  { title: "Deep Rock Galactic", hours: 4.5, tags: ["Co-op", "FPS"], steamAppId: 548430, blurb: "Dwarf miners shoot bugs underground and haul minerals back to the drop pod." },
  { title: "Destiny 2", hours: 134.2, tags: ["FPS", "Co-op"], steamAppId: 1085660, blurb: "A long-running loot shooter of raids, strikes, and space magic." },
  { title: "Dispatch", hours: 15.5, tags: ["Story"], steamAppId: 2592160, blurb: "A superhero workplace comedy where you pick who to send on each call." },
  { title: "ELDEN RING", hours: 11.2, tags: ["RPG", "Action"], steamAppId: 1245620, blurb: "A vast dark-fantasy world you explore and fight through at your own pace." },
  { title: "Europa Universalis IV", hours: null, tags: ["Strategy"], steamAppId: 236850, blurb: "Guide a nation across centuries of diplomacy, trade, and war." },
  { title: "Factorio", hours: 151.6, tags: ["Strategy", "Sim"], steamAppId: 427520, blurb: "Build a factory that never stops growing, then defend it from the locals." },
  { title: "Fallout: New Vegas", hours: 0, tags: ["RPG", "Story"], steamAppId: 22380, blurb: "A desert role-playing game about factions, choices, and who holds the dam." },
  { title: "Foxhole", hours: 3.4, tags: ["Strategy", "Co-op"], steamAppId: 505460, blurb: "A persistent war where players supply, build, and fight on one huge front." },
  { title: "fpsVR", hours: 18.8, tags: ["VR"], steamAppId: 908520, blurb: "A VR overlay that shows how smoothly a headset game is running." },
  { title: "FRUKT", hours: 6.6, tags: ["Sandbox", "Action"], steamAppId: 3880400, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3880400/791f0bd4e57916d7c3300db4660c040ca6b1a7c5/header.jpg", blurb: "A voxel sandbox for shooting, breaking, and ragdolling little people." },
  { title: "Garry's Mod", hours: 0.1, tags: ["Sandbox"], steamAppId: 4000, blurb: "A physics toybox of props, poses, and whatever mods people have built." },
  { title: "GTFO", hours: 47.9, tags: ["Horror", "Co-op"], steamAppId: 493520, blurb: "A hard co-op horror dive: sneak, shoot, and don't wake the nest." },
  { title: "Half-Life: Alyx", hours: 8.6, tags: ["VR", "FPS"], steamAppId: 546560, blurb: "A full VR story in City 17, with hands-on puzzles and close alien fights." },
  { title: "Hearts of Iron IV", hours: 19.5, tags: ["Strategy"], steamAppId: 394360, blurb: "Run a country through World War II, from factories to front lines." },
  { title: "HELLDIVERS™ 2", hours: 68.8, tags: ["Co-op", "FPS"], steamAppId: 553850, blurb: "Drop onto bug and robot planets with friends and try not to team-kill." },
  { title: "Hi-Fi RUSH", hours: null, tags: ["Action"], steamAppId: 1817230, blurb: "A colorful action game where combat, platforms, and music share one beat." },
  { title: "Hogwarts Legacy", hours: 17.1, tags: ["RPG", "Story"], steamAppId: 990080, blurb: "Attend Hogwarts, learn spells, and roam an open wizarding countryside." },
  { title: "ICBM", hours: 5.6, tags: ["Strategy"], steamAppId: 1178220, blurb: "A nuclear-war strategy game about missiles, radar, and who fires first." },
  { title: "ICBM: Escalation", hours: 15, tags: ["Strategy"], steamAppId: 2647680, blurb: "The follow-up: bigger nuclear strategy, with conventional forces in the mix." },
  { title: "Into the Radius 2", hours: 0.6, tags: ["VR", "Survival"], steamAppId: 2307350, blurb: "A VR survival trip into a strange exclusion zone full of anomalies." },
  { title: "Intravenous 2", hours: 4.2, tags: ["Action"], steamAppId: 2608270, blurb: "Top-down stealth where you clear rooms quietly or kick the door in." },
  { title: "It Takes Two", hours: 0, tags: ["Co-op", "Story"], steamAppId: 1426210, blurb: "A two-player adventure about a couple turned into dolls who have to cooperate." },
  { title: "Just Cause 2", hours: null, tags: ["Action", "Sandbox"], steamAppId: 8190, blurb: "Grapple, parachute, and blow up a tropical island because you can." },
  { title: "Just Cause 4 Reloaded", hours: 4, tags: ["Action", "Sandbox"], steamAppId: 517630, blurb: "Tornadoes, grappling hooks, and a map made for causing chaos." },
  { title: "Just Cause™ 3", hours: 7.7, tags: ["Action", "Sandbox"], steamAppId: 225540, blurb: "Wingsuit across Mediterranean towns and liberate them with explosions." },
  { title: "Kerbal Space Program", hours: 0.1, tags: ["Sim"], steamAppId: 220200, blurb: "Build rockets, fail spectacularly, and eventually reach orbit." },
  { title: "Left 4 Dead", hours: null, tags: ["Co-op", "FPS"], steamAppId: 500, blurb: "Four survivors shoot their way through zombie campaigns together." },
  { title: "Left 4 Dead 2", hours: 0.7, tags: ["Co-op", "FPS"], steamAppId: 550, blurb: "The same co-op zombie sprint, with more campaigns, weapons, and melee." },
  { title: "Lethal Company", hours: 37.2, tags: ["Horror", "Co-op"], steamAppId: 1966720, blurb: "A goofy horror job: loot moons with friends and try not to die on quota." },
  { title: "Little Inferno", hours: 8.7, tags: ["Story"], steamAppId: 221260, blurb: "A cozy, weird puzzle about burning toys in a fireplace." },
  { title: "Magic: The Gathering Arena", hours: 1.3, tags: ["Card"], steamAppId: 2141910, blurb: "Digital Magic: build a deck and play short matches against other people." },
  { title: "Marvel Rivals", hours: 10.2, tags: ["FPS"], steamAppId: 2767030, blurb: "A Marvel hero shooter of team fights, ultimates, and familiar characters." },
  { title: "Marvel’s Spider-Man Remastered", hours: 74.3, tags: ["Action", "Story"], steamAppId: 1817070, blurb: "Swing through New York, fight crime, and follow a full Spider-Man story." },
  { title: "MECCHA CHAMELEON", hours: 0.6, tags: ["Party"], steamAppId: 4704690, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4704690/163e2a742e5fb8e1f5d1e3a890da98f04ab809d4/header.jpg", blurb: "Hide-and-seek where you paint your body to blend into the room." },
  { title: "METAL GEAR SOLID V: GROUND ZEROES", hours: 2.8, tags: ["Action"], steamAppId: 311340, blurb: "A short, tense stealth prologue set in one rainy camp." },
  { title: "METAL GEAR SOLID V: THE PHANTOM PAIN", hours: 67.3, tags: ["Action", "Sandbox"], steamAppId: 287700, blurb: "Open-world stealth: sneak, extract soldiers, and build your own base." },
  { title: "My Friend Pedro", hours: 1.6, tags: ["Action"], steamAppId: 557340, blurb: "Slow-motion gun ballet guided by a talking banana." },
  { title: "MY HERO ULTRA RUMBLE", hours: 4.6, tags: ["Action"], steamAppId: 1607250, blurb: "A My Hero Academia battle royale of quirks, teams, and last-person standing." },
  { title: "No Man's Sky", hours: 3.2, tags: ["Survival", "Sandbox"], steamAppId: 275850, blurb: "Fly between planets, gather resources, and wander a generated universe." },
  { title: "Noita", hours: 11.4, tags: ["Action"], steamAppId: 881100, blurb: "Every pixel is simulated, and your wand will probably kill you first." },
  { title: "Once Human", hours: 1.4, tags: ["Survival", "Co-op"], steamAppId: 2139460, blurb: "A shared survival world of anomalies, bases, and strange powers." },
  { title: "OpenTTD", hours: null, tags: ["Sim", "Strategy"], steamAppId: 1536610, blurb: "Build a transport company of trains, roads, and planes across a growing map." },
  { title: "Ori and the Will of the Wisps", hours: 3.7, tags: ["Action", "Story"], steamAppId: 1057090, blurb: "A beautiful platformer about a small spirit, tough jumps, and a quiet story." },
  { title: "Oxygen Not Included", hours: 1.4, tags: ["Sim", "Strategy"], steamAppId: 457140, blurb: "Keep tiny colonists alive underground: air, food, heat, and plumbing." },
  { title: "Paladins®", hours: 1.8, tags: ["FPS"], steamAppId: 444090, blurb: "A free hero shooter with champions, abilities, and short team matches." },
  { title: "Path of Exile 2", hours: 24.7, tags: ["RPG", "Action"], steamAppId: 2694490, blurb: "A deep action RPG of loot, skill gems, and dangerous maps." },
  { title: "PAYDAY 2", hours: 1.4, tags: ["Co-op", "FPS"], steamAppId: 218620, blurb: "Plan a heist with friends, then shoot your way out when it goes wrong." },
  { title: "PEAK", hours: 0.5, tags: ["Co-op"], steamAppId: 3527290, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3527290/31bac6b2eccf09b368f5e95ce510bae2baf3cfcd/header.jpg", blurb: "Climb a deadly mountain with friends, where one slip can end the run." },
  { title: "People Playground", hours: 330.8, tags: ["Sandbox"], steamAppId: 1118200, blurb: "A physics playground for spawning people, weapons, and ridiculous experiments." },
  { title: "Phasmophobia", hours: 1.2, tags: ["Horror", "Co-op"], steamAppId: 739630, blurb: "Hunt ghosts in the dark with friends, a flashlight, and bad ideas." },
  { title: "Planetary Annihilation: TITANS", hours: 1.9, tags: ["RTS"], steamAppId: 386070, blurb: "Planet-scale real-time strategy, including giant robots that walk on maps." },
  { title: "R.E.P.O.", hours: 7.4, tags: ["Horror", "Co-op"], steamAppId: 3241660, blurb: "A co-op horror job hauling haunted junk while something hunts the crew." },
  { title: "Ready or Not", hours: 13, tags: ["FPS", "Sim"], steamAppId: 1144200, blurb: "Slow, serious SWAT raids where planning matters more than running in." },
  { title: "RimWorld", hours: 6.4, tags: ["Strategy", "Sim"], steamAppId: 294100, blurb: "A colony story generator of survivors, disasters, and bad decisions." },
  { title: "Sea of Thieves: 2026 Edition", hours: 2.3, tags: ["Co-op"], steamAppId: 1172620, blurb: "Sail, dig up loot, and get into pirate fights with a small crew." },
  { title: "Sid Meier’s Civilization® VI", hours: 118.8, tags: ["Strategy"], steamAppId: 289070, blurb: "One more turn of building an empire, from a hut to a space race." },
  { title: "Sonic Frontiers", hours: 19.9, tags: ["Action"], steamAppId: 1237320, blurb: "Open-zone Sonic: run fast, fight titans, and chase a lighter story." },
  { title: "Sons Of The Forest", hours: 1.2, tags: ["Survival", "Horror"], steamAppId: 1326470, blurb: "Survive on a cannibal island, build shelter, and uncover what is underground." },
  { title: "Soundpad", hours: 4.3, tags: ["Party"], steamAppId: 629520, blurb: "A soundboard for playing clips in voice chat, not a game you finish." },
  { title: "South Park™: The Fractured But Whole™", hours: null, tags: ["RPG", "Story"], steamAppId: 488790, blurb: "A rude South Park comedy where the kids play superheroes in turn-based fights." },
  { title: "South Park™: The Stick of Truth™", hours: 11.4, tags: ["RPG", "Story"], steamAppId: 213670, blurb: "A short, filthy South Park RPG about a stick, wizards, and the new kid." },
  { title: "Split Fiction", hours: null, tags: ["Co-op", "Story"], steamAppId: 2001120, blurb: "A two-player story that jumps between sci-fi and fantasy set pieces." },
  { title: "STAR WARS Zero Company™", hours: null, tags: ["Strategy"], steamAppId: 2075800, cover: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2075800/2c7d5dad080c4888faaa03c4a955136c50f5bfae/header.jpg", blurb: "Turn-based Star Wars squad tactics at the end of the Clone Wars." },
  { title: "STAR WARS™ Battlefront™ II", hours: 4.5, tags: ["FPS"], steamAppId: 1237950, blurb: "Big Star Wars battles on foot, in ships, and as famous heroes." },
  { title: "Stardew Valley", hours: 0.8, tags: ["Sim", "Co-op"], steamAppId: 413150, blurb: "A calm farm life of crops, townsfolk, mines, and optional co-op." },
  { title: "Stronghold Crusader Extreme HD", hours: null, tags: ["RTS"], steamAppId: null, blurb: "Castle defense with huge crusader battles and endless enemy waves." },
  { title: "Stronghold Crusader HD (2012)", hours: 6.5, tags: ["RTS"], steamAppId: 40970, blurb: "Build a desert castle, manage gold, and withstand siege after siege." },
  { title: "Subnautica", hours: 13.1, tags: ["Survival"], steamAppId: 264710, blurb: "Crash on an ocean planet and dive deeper while something huge lives below." },
  { title: "Subnautica 2", hours: null, tags: ["Survival"], steamAppId: 1962700, blurb: "The next ocean survival story: explore, craft, and fear the deep." },
  { title: "Supreme Commander", hours: null, tags: ["RTS"], steamAppId: 9350, blurb: "Enormous robot armies on maps so big you zoom from planet to soldier." },
  { title: "Supreme Commander: Forged Alliance", hours: 646, tags: ["RTS"], steamAppId: 9420, blurb: "The same giant-scale strategy, tuned into the one with hundreds of hours." },
  { title: "Tabletop Simulator", hours: 2.4, tags: ["Party", "Sim"], steamAppId: 286160, blurb: "A virtual table for board games, cards, and whatever you load onto it." },
  { title: "Tactical Assault VR", hours: 3.2, tags: ["VR", "FPS"], steamAppId: 2314160, blurb: "A VR SWAT game of stacking up, breaching doors, and clearing rooms." },
  { title: "TEKKEN 8", hours: 7.3, tags: ["Fighting"], steamAppId: 1778820, blurb: "A 3D fighter of long combos, rivalries, and one-on-one matches." },
  { title: "Terraria", hours: 21.6, tags: ["Sandbox", "Survival"], steamAppId: 105600, blurb: "Dig, build, and fight bosses in a huge 2D world." },
  { title: "THE FINALS", hours: 24, tags: ["FPS"], steamAppId: 2073850, blurb: "A destruction shooter where teams smash buildings to win the cashout." },
  { title: "The First Descendant", hours: 0.3, tags: ["FPS", "Co-op"], steamAppId: 2074920, blurb: "A looter shooter of flashy descendants, bosses, and co-op missions." },
  { title: "The Forest", hours: 0.1, tags: ["Survival", "Horror"], steamAppId: 242760, blurb: "Survive a cannibal peninsula, build a camp, and look for a missing son." },
  { title: "The Matchless Kungfu", hours: 1, tags: ["RPG", "Sandbox"], steamAppId: 1696440, blurb: "An open martial-arts sandbox where you wander, train, and pick a life." },
  { title: "The Outlast Trials", hours: 6.8, tags: ["Horror", "Co-op"], steamAppId: 1304930, blurb: "Co-op horror trials in a gruesome facility that wants you to suffer on camera." },
  { title: "The Riftbreaker", hours: 0.2, tags: ["Action", "Strategy"], steamAppId: 780310, blurb: "Hack aliens in a mech while your base automates the alien planet behind you." },
  { title: "The Walking Dead: The Telltale Definitive Series", hours: 1.4, tags: ["Story"], steamAppId: 1449690, blurb: "A choice-driven zombie story about Clementine and the people she meets." },
  { title: "theHunter: Call of the Wild™", hours: 0.3, tags: ["Sim"], steamAppId: 518790, blurb: "A quiet hunting sim of tracking animals across large reserves." },
  { title: "Titanfall® 2", hours: 13.4, tags: ["FPS", "Action"], steamAppId: 1237970, blurb: "Wall-running pilots and mechs, plus a short campaign people love." },
  { title: "tModLoader", hours: 19.6, tags: ["Sandbox"], steamAppId: 1281930, blurb: "Terraria with mods: new bosses, classes, and whole extra games inside it." },
  { title: "Tom Clancy's Ghost Recon® Breakpoint", hours: null, tags: ["FPS", "Action"], steamAppId: 2231380, blurb: "Sneak or shoot across an island as a special-forces squad." },
  { title: "Tom Clancy's Ghost Recon® Wildlands", hours: 10, tags: ["FPS", "Action"], steamAppId: 460930, blurb: "An open Bolivia where you dismantle a cartel by land, air, or stealth." },
  { title: "Tom Clancy's Rainbow Six Siege", hours: 463.4, tags: ["FPS"], steamAppId: 359550, blurb: "Close-quarters attacker-defender rounds built around gadgets and site setups." },
  { title: "Tom Clancy's Rainbow Six Siege - Test Server", hours: null, tags: ["FPS"], steamAppId: null, blurb: "The test build of Siege, used to try changes before they hit the real game." },
  { title: "Tom Clancy’s Rainbow Six® Extraction", hours: 8.1, tags: ["Co-op", "FPS"], steamAppId: 2379390, blurb: "Siege operators on co-op missions against an alien parasite." },
  { title: "Tom Clancy’s The Division® 2", hours: 9.5, tags: ["FPS", "Co-op"], steamAppId: 2221490, blurb: "A loot shooter set in a collapsed Washington, played solo or in a squad." },
  { title: "ULTRAKILL", hours: 0.8, tags: ["FPS", "Action"], steamAppId: 1229490, blurb: "A fast, violent shooter about style, movement, and not touching the ground." },
  { title: "Unravel Two", hours: 0.4, tags: ["Co-op", "Story"], steamAppId: 1225570, blurb: "Two yarn characters solve gentle puzzles, best played side by side." },
  { title: "VRChat", hours: 1.1, tags: ["VR", "Sandbox"], steamAppId: 438100, blurb: "Hang out in user-made virtual worlds, with or without a headset." },
  { title: "VTOL VR", hours: 2.7, tags: ["VR", "Sim"], steamAppId: 667970, blurb: "Fly military aircraft in VR, with the switches actually under your hands." },
  { title: "Wallpaper Engine", hours: 10.7, tags: ["Sandbox"], steamAppId: 431960, blurb: "Animated desktop wallpapers. It lives in the library, but it is not a game." },
  { title: "War Robots: Frontiers", hours: 6.4, tags: ["Action", "FPS"], steamAppId: 1491000, blurb: "Online mech battles where you build a robot and drop into squad fights." },
  { title: "War Thunder", hours: 17.1, tags: ["Sim"], steamAppId: 236390, blurb: "Plane, tank, and ship battles that can be arcade-fast or painfully realistic." },
  { title: "Warframe", hours: 74.2, tags: ["Action", "Co-op"], steamAppId: 230410, blurb: "A fast space-ninja looter with years of missions, frames, and co-op." },
  { title: "Wargame: Red Dragon", hours: 16.9, tags: ["RTS", "Strategy"], steamAppId: 251060, blurb: "Cold War units on large maps, where recon and range matter more than rushing." },
  { title: "Warhammer 40,000: Space Marine 2", hours: 32.4, tags: ["Action", "Co-op"], steamAppId: 2183900, blurb: "Play a super-soldier cutting through alien swarms, alone or with two friends." },
  { title: "Warhammer: Vermintide 2", hours: null, tags: ["Co-op", "Action"], steamAppId: 552500, blurb: "Four-player melee against endless rat-men, with a little magic on the side." },
  { title: "WARNO", hours: 76.1, tags: ["RTS"], steamAppId: 1611600, blurb: "A Cold War gone hot, fought in detailed real-time battles." },
  { title: "White Knuckle Demo", hours: 3.7, tags: ["Horror", "Action"], steamAppId: 3218540, blurb: "Climb a terrifying concrete shaft as fast as you can, and don't look down." },
  { title: "World of Tanks Blitz", hours: 10.4, tags: ["Action"], steamAppId: 444200, blurb: "Short tank battles on smaller maps, quicker than the full World of Tanks." },
  { title: "WorldBox - God Simulator", hours: 0.6, tags: ["Sandbox", "Sim"], steamAppId: 1206560, blurb: "Drop civilizations on a map and watch, or ruin them with disasters." },
  { title: "XCOM® 2", hours: 22.5, tags: ["Strategy"], steamAppId: 268500, blurb: "Turn-based alien war where every soldier you name can die for good." }
];
